getraenke = ['einen Kaffee in einer Tasse aus blauem Porzelan','eine Limonade in einem Cocktailglas mit Schirmchen',
             'einen Kakao in einer großen lila Tasse mit Löffel','einen losen Tee in einem Gaiwan',
             'eine Cola mit einer Scheibe Zitrone in einem Glas mit Schirmchen',
             'kaltes Wasser','kalten selbsgemachten Eistee',
             'frischen Mate in einem Kürbis mit einem verschnörkelten Strohhalm',
             'eine Club Mate','einen frisch gepressten Apfelsaft','einen frisch gepressten Traubensaft',
             'einen Kiwismoothie', 'einen frisch gepressten Orangensaft','einen Coconut Kiss in einem hohen Cocktailglas mit einer Scheibe Ananas am rand',
             'ein Glas Milch', 'einen Erdbeersmoothie', 'einen Latte Macchiato mit einem Keks neben der Tasse',
             'eine Tasse heiße Schokolade aus Schokostückcohen','einen Mango-Melone-Smoothie','ein Glas feinster Hoffnung',
             'einen frischen Pfefferminztee','eine Eisschokolade mit Sahne','einen Eiskaffee mit Sahne',
             'einen kalten Milchshake mit deinem Lieblingseis',
             'eine kalte Afri Cola','ein Sojamilch Milchkaffee mit einem Keks neben der Tasse',
             'einen Soja Latte Machiato mit einem Keks neben der Tasse', 'einen Monster Energy Drink in der Dose',
             'einen Blaubeersmoothie','ein kaltes Spezi mit einer Scheibe Zitrone am Rand', 'eine Karaffe kaltes Sprudelwasser',
             'einen großen Becher Kirsch-Banane-Nektar',
             'einen kalten Rockstar Energy', 'eine Mio Mio Mate',
             'eine Fritz!Cola', 'eine Sprite mit Zitrone am Glaß',
             'eine Fanta mit Orange am Glaß', 'ein leckeres Wasser', 'ein edles Glas Kokosnussmilch',
             'eine Tasse lauwarmen Sencha','ein Glas Chai Latte mit Sojamilch','ein Tässchen kalten Sencha',
             'einen Cappuccino mit einem Keks neben der Tasse','eine Tasse Cashew-Milch mit einem schokokeks neben der Tasse',
             'eine Karaffe Hoffnung','ein Glas Zuversich','eine Flasche Paulaner Spezi',
             'eine edle Tasse Soja-Kakao','eine Flasche Bionade Holunder',
             'einen Eiskalten Tehere',
             'einen kalt gezogenen grünen Tee',
             'eine edle Tasse frischen Kaffee mit Sojamilch','ein Glas frisch gepressten Traubensaft'
                ]
