getraenke = ['einen Kaffee','eine Limonade','einen Kakao','einen Tee',
                     'einen Kräutertee','eine Cola',
                     'kaltes Wasser','kalten Eistee','einen Raktajino',
                     'frischen Mate', 'eine Club Mate','ein Glas Gurkenwasser',
                     'einen Energydrink','einen Apfelsaft','einen Traubensaft',
                     'einen Muckefuck','einen Kiwismoothie', 'einen Spinatsmoothie',
                     'einen Orangensaft','einen Coconut Kiss','ein Glas Milch',
                     'einen Erdbeersmoothie','einen Kirschsaft',
                     'einen Latte Macchiato','eine Tasse heiße Schokolade',
                     'ein Glas Sauerkrautwasser','einen Topf Kinderpunsch',
                     'einen Mango-Melonesmoothie','ein Glas Hoffnung',
                     'einen frischen Pfefferminztee','eine Eisschokolade',
                     'einen Eiskaffee','einen kalten Milchshake',
                     'eine kalte Afri Cola','ein Soja-Milch Milchkaffee',
                     'einen Soja Latte Machiato', 'einen Monster Energy Drink',
                     'einen Fraktal Allmachtstrank', 'einen Heiltrank',
                     'einen großen Becher Blumenwasser', 'einen Erdbeershake',
                     'einen Blaubeersmoothie', 'eine Tasse Pfefferminztee',
                     'ein kaltes Spezi', 'eine Tasse Hanftee',
                     'eine Karaffe Sprudelwasser', 
                     'einen kleinen Becher Kirsch-Banane-Nektar',
                     'einen Rockstar Energy', 'eine Mio Mio Mate',
                     'eine Fritz!Cola', 'einen Ginger-Ale',
                     'ein Butterbier', 'ein Glas laktosefreie Milch',
                     'einen Lebertran', 'eine Caprisonne',
                     'einen Kürbissaft', 'einen Kefir',
                     'einen Ayran', 'ein Glas Nihilismus', 'eine Sprite', 
                     'eine Fanta', 'einen Purple Flurp', 'einen Booster Energy',
                     'ein leckeres Wasser', 'einen Robby Bubble', 'ein Glas warme Milch',
                     'ein Glas Schlamm', 'ein Glas Regenwasser', 'ein halbes Glas Kokosnussmilch',
                     'ein Glas Ingwerwasser','eine Tasse lauwarmen Sencha',
                     'ein Glass Chai Latte mit Sojamilch','ein Tässchen kalten Sencha',
                     'einen Cappucino','eine Tasse Cashew-Milch']
