getraenke = ['einen Kaffee','eine Limonade','einen Kakao','einen Tee',
                     'einen Kräutertee','eine Cola',
                     'kaltes Wasser','kalten Eistee','einen Raktajino',
                     'frischen Mate', 'eine Club Mate','ein Glas Gurkenwasser',
                     'einen Energydrink','einen Apfelsaft','einen Traubensaft',
                     'einen Muckefuck','einen Kiwismoothie', 'einen Spinatsmoothie',
                     'einen Orangensaft','einen Coconut Kiss','ein Glas Milch',
                     'einen Erdbeersmoothie','einen Kirschsaft',
                     'einen Latte Macchiato','eine Tasse heiße Schokolade',
                     'ein Glas Sauerkrautwasser','einen Topf Kinderpunsch',
                     'einen Mango-Melone-Smoothie','ein Glas Hoffnung',
                     'einen frischen Pfefferminztee','eine Eisschokolade',
                     'einen Eiskaffee','einen kalten Milchshake',
                     'eine kalte Afri Cola','ein Sojamilch Milchkaffee',
                     'einen Soja Latte Machiato', 'einen Monster Energy Drink',
                     'einen Fraktal Allmachtstrank', 'einen Heiltrank',
                     'einen großen Becher Blumenwasser', 'einen Erdbeershake',
                     'einen Blaubeersmoothie', 'eine Tasse Pfefferminztee',
                     'ein kaltes Spezi', 'eine Tasse Hanftee',
                     'eine Karaffe Sprudelwasser', 
                     'einen kleinen Becher Kirsch-Banane-Nektar',
                     'einen Rockstar Energy', 'eine Mio Mio Mate',
                     'eine Fritz!Cola', 'ein Ginger-Ale',
                     'ein Butterbier', 'ein Glas laktosefreie Milch',
                     'einen Lebertran', 'eine Caprisonne',
                     'einen Kürbissaft', 'einen Kefir',
                     'einen Ayran', 'ein Glas Nihilismus', 'eine Sprite', 
                     'eine Fanta', 'einen Purple Flurp', 'einen Booster Energy',
                     'ein leckeres Wasser', 'einen Robby Bubble', 'ein Glas warme Milch',
                     'ein Glas Schlamm', 'ein Glas Regenwasser', 'ein halbes Glas Kokosnussmilch',
                     'ein Glas Ingwerwasser','eine Tasse lauwarmen Sencha',
                     'ein Glas Chai Latte mit Sojamilch','ein Tässchen kalten Sencha',
                     'einen Cappuccino','eine Tasse Cashew-Milch',
                     'eine Karaffe Hoffnung', 'eine Kanne Zuversicht','ein Glas Zuversicht',
                     'ein Soja-Chai-Latte (Kids Temperature)','eine Flasche Paulaner Spezi',
                     'einen Pappbecher Soja-Kakao','eine Flasche Bionade Holunder',
                     'einen Eiskalten Tehere', 'eine Runde Wasser für alle',
                     'einen kalt gezogenen grünen Tee','ein Glas Brackwasser',
                     'einen Pappbecher frischen Kaffee mit Sojamilch','einen Becher des Lieblingsgetränkes',
                     'ein Glas frisch gepressten Traubensaft','ein Glas mit zimmerwarmer Hafermilchschokolade',
                     'eine Bierglas mit Fassbrause','einen Bubble Tea in einem billigen Plastikbecher',
                     'eine Tasse Roibostee', 'ein Rainbow-Cocktail', 'einen virgin Sunrise', 'eine Dose Monster rehab'
                     'eine Energy-Cola', 'eine Apfelschorle','einen Birnensaft','einen Mangosaft',
                     'ein Glas Holunderblütensirup', 'eine Sauerkirschlimo', 'ein Glaß gefrorenes Wasser',
                     'eine bunte Tasse fairtrade Bohnenkaffe','einen Maracujasaft','ein Glas Luft',
                     'ein Glas Fairtrade Limonade'
                ]
